http://127.0.0.1:3000/

### get all users in user table
http://127.0.0.1:3000/profile

### DONE IN FRONTEND
http://127.0.0.1:3000/profile/638cbcfd7155f42bea703fb2

###
POST http://127.0.0.1:3000/profile/638cbcfd7155f42bea703fb2
Content-Type: application/json

{
    "email":"Bob@yahoo.com",
    "bio":"Hi my name is Bob"
}

###
DELETE http://127.0.0.1:3000/profile/638cbcfd7155f42bea703fb2/638cbcfd7155f42bea703fb2


### TEST exercise log, GET ALL POST USE USERID
GET http://127.0.0.1:3000/post/638cbcfd7155f42bea703fb2

### ADD POST
POST http://127.0.0.1:3000/post/
Content-Type: application/json

{
    "userId":"638cbe4a7155f42bea703fb9",
    "image":"url to image",
    "caption":"THIS IS TOM POST"
}

###, json
DELETE http://127.0.0.1:3000/post/638cf4aae97620c1b7d7b7c9

###, json
PATCH http://127.0.0.1:3000/post/638cf509645e4a6b07549f56

### TEST auth route, return json, DONE IN FRONTEND
POST http://127.0.0.1:3000/auth/register
Content-Type: application/json

{
    "username":"Doug",
    "password":"doug123"
}

### TEST login, return json, DONE in frontend
POST http://127.0.0.1:3000/auth/login
Content-Type: application/json

{
    "username":"Bob",
    "password":"bob123"
}