http://127.0.0.1:3000/

###
http://127.0.0.1:3000/profile

###
http://127.0.0.1:3000/profile/638cbcfd7155f42bea703fb2


###
POST http://127.0.0.1:3000/profile/638cbcfd7155f42bea703fb2
Content-Type: application/json

{
    "email":"Bob@yahoo.com",
    "bio":"Hi my name is Bob"
}

###
DELETE http://127.0.0.1:3000/profile/638cbcfd7155f42bea703fb2/638cbcfd7155f42bea703fb2


### TEST exercise log
GET http://127.0.0.1:3000/post/638cf4aae97620c1b7d7b7c9

###
POST http://127.0.0.1:3000/post/
Content-Type: application/json

{
    "userId":"638cbe4a7155f42bea703fb9",
    "image":"url to image",
    "caption":"THIS IS TOM POST"
}

